---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  # Resource for your application source code
  - name: source
    type: git
    source:
      uri: https://github.com/buildpacks/samples.git
      branch: master
      paths: [apps/java-maven]

  - name: tasks
    type: git
    source:
      uri: https://github.com/ameyer-pivotal/concourse-cnb-tasks.git
      branch: wip #master

jobs:
  - name: build
    plan:
      - get: source
        trigger: true

      - get: tasks

      # Run detect phase
      - task: detect
        file: tasks/detect/task.yml
        params:
          # Only needed if app is not in root of repo
          SOURCE_SUBDIR: apps/java-maven
