# TODO: CNB_PLATFORM_API
# TODO: Caching
---
resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  # Your application source code
  - name: source
    type: git
    source:
      uri: ((source_repo))
      branch: master
      paths: [((source_subdir))]

  # Builder image to use
  - name: builder
    type: docker-image
    source:
      repository: ((builder_image))
      tag: ((builder_tag))

  # Resource for cache
  # TODO

  - name: tasks
    type: git
    source:
      uri: https://github.com/ameyer-pivotal/concourse-cnb-tasks.git
      branch: wip #master

jobs:
  - name: build
    plan:
      - get: source
        trigger: true
      - get: builder
      - get: tasks

      # Set up permissions for resource dirs
      - task: prepare
        file: tasks/prepare/task.yml

      # Run detect phase
      - task: detect
        image: builder
        file: tasks/detect/task.yml
        params:
          SOURCE_SUBDIR: ((source_subdir))
      
      # Run analyze phase
      - task: analyze
        image: builder
        file: tasks/analyze/task.yml
        params:
          IMAGE_NAME: ((image_name))
